teacher:
  CrossNet:
    embedding_dim: 20
    L2: 1.e-5
    depth: 4
  DNN:
    embedding_dim: 20
    L2: 1.e-5
    hidden_dims: [1000, 1000, 1000, 1000, 1000, 780, 1]
    dropout: 0.1
student:
  embedding_dim: 20
  L2: 1.e-5
  depth: 1