teacher:
  smore:
    embedding_dim: 500
    n_ui_layers: 2
    knn_k: 5
    n_mm_layers: 1
    reg_weight: 1.e-6
    cl_weight: 0.01
    dropout: 0.1
student:
  embedding_dim: 500
  n_ui_layers: 2
  knn_k: 5
  n_mm_layers: 1
  reg_weight: 1.e-6
  cl_weight: 0.01
  dropout: 0.1