teacher:
  init_std: 0.1
  keep_prob: 0.6
  A_split: False
  dropout: False
  embedding_dim: 200
  num_layers: 2
student:
  init_std: 0.1
  keep_prob: 0.6
  A_split: False
  dropout: False
  embedding_dim: 20
  num_layers: 2