bm3:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 1.0
  norm: True
  adafreq_K: 5
  adafreq_keep_prob: 0.3
  adafreq_dropout_rate: 0.2
  hidden_dim_ratio: 1
mgcn:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 1.0
  norm: True
  adafreq_K: 5
  adafreq_keep_prob: 0.3
  adafreq_dropout_rate: 0.2
  hidden_dim_ratio: 1
lgmrec:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 1.0
  norm: True
  adafreq_K: 5
  adafreq_keep_prob: 0.3
  adafreq_dropout_rate: 0.2
  hidden_dim_ratio: 1
smore:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 1.0
  norm: True
  adafreq_K: 5
  adafreq_keep_prob: 0.3
  adafreq_dropout_rate: 0.2
  hidden_dim_ratio: 1