bm3:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 1.0
  norm: True
  freqmm_K: 5
  freqmm_alpha: 0.7
  freqmm_keep_prob: 0.3
  freqmm_dropout_rate: 0.2
  hidden_dim_ratio: 1
mgcn:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 1.0
  norm: True
  freqmm_K: 3
  freqmm_alpha: 0.7
  freqmm_keep_prob: 0.3
  freqmm_dropout_rate: 0.2
  hidden_dim_ratio: 5
lgmrec:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 0.5
  norm: True
  freqmm_K: 3
  freqmm_alpha: 0.7
  freqmm_keep_prob: 0.3
  freqmm_dropout_rate: 0.2
  hidden_dim_ratio: 1
smore:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 0.5
  norm: True
  freqmm_K: 3
  freqmm_alpha: 0.7
  freqmm_keep_prob: 0.3
  freqmm_dropout_rate: 0.2
  hidden_dim_ratio: 1