epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-5
lmbda: 0.005

de_end_T: 1.e-10
de_anneal_size: 1.e+10
de_num_experts: 20

cpd_alpha: 0.05
cpd_sample_type: rank  # uniform, batch, rank
cpd_reg_type: list  # pair, list
cpd_guide_type: teacher   # student, teacher

# For cpd_sample_type == "rank"
cpd_T: 10
cpd_mxK: 500

# For cpd_reg_type == "list"
cpd_Q: 5
cpd_tau_ce: 0.01