teacher:
  bpr:
    init_std: 1.e-2
    embedding_dim: 400
  lightgcn:
    init_std: 0.1
    keep_prob: 0.6
    A_split: False
    dropout: False
    embedding_dim: 2000
    num_layers: 3
  simplex:
    init_std: 1.e-4
    embedding_dim: 500
    simplex_dropout_rate: 0.1
    simplex_similarity_score: cosine
    simplex_gamma: 0.6
    simplex_margin: 0.1
    simplex_max_len: 500
    simplex_negative_weight: 100
    simplex_enable_bias: False
  hstu:
    max_sequence_len: 100
    embedding_dim: 64
    num_blocks: 8
    num_heads: 4
    attention_dim: 8
    linear_dim: 16
    linear_activation: silu
    linear_dropout_rate: 0.5
    attn_dropout_rate: 0.
    enable_relative_attention_bias: True
    concat_ua: False
    normalization: rel_bias
    max_output_len: 10
    num_negatives: 512
    dropout_rate: 0.5
    temperature: 0.05
student:
  init_std: 1.e-2
  embedding_dim: 20