epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-8
lmbda: 0.5

filterd_num_experts: 5
filterd_K: 5
filterd_alpha: 0.7
filterd_dropout_rate: 0.2
filterd_type: smooth  # smooth, rough
filterd_eig_ratio: 1.0
filterd_beta: 1.