bpr:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-3 # sess 13 + sess kd mid
  lmbda: 0.5  # sess kd
  freqdall_beta: 0.5  # sess 1 + sess kd mid
  freqall_K: 50 # sess 2 + sess kd mid
  freqall_alpha_logit: 0.7  # sess 3 + sess kd mid
  freqall_norm: True
  freqall_knn: 5
  freqall_alpha_feat: 0.5 # sess 4 + sess kd mid
  freqall_keep_prob: 0.5
  freqall_dropout_rate: 0.2 # sess 14 up + sess kd mid
  hidden_dim_ratio: 5 # sess 14 down + sess kd mid