bpr:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 5.0
  kd_tau: 1
  kd_K: 200
  kd_guide: student
lightgcn:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 5
  kd_tau: 10
  kd_K: 50
  kd_guide: student
simplex:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 50
  kd_tau: 1
  kd_K: 100
  kd_guide: student