bpr:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 5
  mkd_tau: 1
  mkd_K: 50
  mkd_L: 50
  mkd_T: 10
  mkd_mxK: 100
  mkd_beta: 5
lightgcn:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 5
  mkd_tau: 1
  mkd_K: 50
  mkd_L: 50
  mkd_T: 10
  mkd_mxK: 100
  mkd_beta: 5
simplex:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-5
  lmbda: 5
  mkd_tau: 1
  mkd_K: 50
  mkd_L: 50
  mkd_T: 10
  mkd_mxK: 100
  mkd_beta: 5