bpr:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 5.0
  mkd_tau: 1
  mkd_K: 100
  mkd_wT: 0
  mkd_wa: 1.0
lightgcn:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 30
  mkd_tau: 10
  mkd_K: 50
  mkd_wT: 0
  mkd_wa: 0.1
simplex:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-7
  lmbda: 50
  mkd_tau: 1
  mkd_K: 100
  mkd_wT: 0
  mkd_wa: 2.0