teacher:
  model: DeepFM
  batch_norm: false
  embedding_dim: 20
  embedding_regularizer: 1.0e-05
  hidden_activations: relu
  hidden_units: [64, 32]
  net_dropout: 0.2
  net_regularizer: 0
student:
  model: DNN
  batch_norm: false
  embedding_dim: 20
  embedding_regularizer: 1.0e-05
  hidden_activations: relu
  hidden_units: [32]
  net_dropout: 0.2
  net_regularizer: 0