teacher:
  dnn:
    embedding_dim: 20
    hidden_dims: [1000, 1000, 1000, 1000, 1000, 780, 1]
    dropout: 0.1
  crossnet:
    embedding_dim: 20
    depth: 4
student:
  embedding_dim: 20
  hidden_dims: [64, 32, 1]
  dropout: 0.1