teacher:
  DNN:
    embedding_dim: 20
    L2: 1.e-5
    hidden_dims: [1000, 1000, 1000, 1000, 1000, 780, 1]
    dropout: 0.1
  CrossNet:
    embedding_dim: 20
    L2: 1.e-5
    depth: 4
student:
  embedding_dim: 20
  L2: 1.e-5
  hidden_dims: [64, 32, 1]
  dropout: 0.1