teacher:
  mgcn:
    embedding_dim: 1000
    n_ui_layers: 2
    knn_k: 5
    n_mm_layers: 1
    reg_weight: 1.e-6
    cl_weight: 0.01
student:
  embedding_dim: 20
  n_ui_layers: 2
  knn_k: 10
  n_mm_layers: 1
  reg_weight: 0.0001
  cl_weight: 1