teacher:
  model: EulerNet
  embedding_dim: 20
  L2: 1.e-5
  order_list: [39, 39]
  eulernet_norm: True
  eulernet_dropex: 0.1
  eulernet_dropim: 0.2
student:
  model: DNN
  embedding_dim: 20
  L2: 1.e-5
  hidden_dims: [64, 32, 1]
  dropout: 0.1