teacher:
  eulernet:
    embedding_dim: 20
    order_list: [39, 39]
    eulernet_norm: True
    eulernet_dropex: 0.1
    eulernet_dropim: 0.2
student:
  embedding_dim: 20
  order_list: [39]
  eulernet_norm: True
  eulernet_dropex: 0.1
  eulernet_dropim: 0.2