teacher:
  sccf:
    no_neg_sampling: True
    embedding_dim: 2000
    sccf_temperature: 0.1
  bpr:
    init_std: 1.e-2
    embedding_dim: 400
  lightgcn:
    init_std: 0.1
    keep_prob: 0.6
    A_split: False
    dropout: False
    embedding_dim: 2000
    num_layers: 3
student:
  no_neg_sampling: True
  embedding_dim: 20
  sccf_temperature: 0.1