teacher:
  bpr:
    init_std: 1.e-2
    embedding_dim: 300
  lightgcn:
    init_std: 0.1
    keep_prob: 0.6
    A_split: False
    dropout: False
    embedding_dim: 1000
    num_layers: 3
student:
  init_std: 1.e-2
  embedding_dim: 20