teacher:
  bm3:
    embedding_dim: 500
    n_layers: 2
    reg_weight: 0.0001
    cl_weight: 5
    dropout: 0.5
student:
  embedding_dim: 300
  n_layers: 2
  reg_weight: 0.1
  cl_weight: 2.0
  dropout: 0.5