teacher:
  lgmrec:
    embedding_dim: 1000
    n_ui_layers: 2
    n_mm_layers: 1
    n_hyper_layer: 1
    hyper_num: 4
    alpha: 0.1
    reg_weight: 0.0001
    cl_weight: 5
    dropout: 0.5
student:
  embedding_dim: 500
  n_ui_layers: 2
  n_mm_layers: 1
  n_hyper_layer: 1
  hyper_num: 4
  alpha: 0.3
  reg_weight: 0.0001
  cl_weight: 5
  dropout: 0.5