lightgcn:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-3
  lmbda: 5.0  # done
  freqdall_beta: 0.5  # sess 1 + kd down
  freqall_K: 50 # done
  freqall_alpha_logit: 0.7  # sess 3 + kd up
  freqall_norm: True
  freqall_knn: 5
  freqall_alpha_feat: 0.5
  freqall_keep_prob: 0.5
  freqall_dropout_rate: 0.2
  hidden_dim_ratio: 5 # sess 14 + kd down