epochs: 1000
batch_size: 2048
lr: 1.e-3
wd: 1.e-8
lmbda: 0.5

graphd_num_experts: 5
graphd_K: 5
graphd_alpha: 0.7
graphd_keep_prob: 0.7
graphd_dropout_rate: 0.2

gdcp_reg_type: "second"
gdcp_w_reg: 0.1
gdcp_dec_epoch: 30

gdcp_margin: 0.

gdcp_Q: 50
gdcp_T: 10
gdcp_mxK: 1000
gdcp_tau_ce: 0.1