teacher:
  epochs: 1000
  batch_size: 256
  lr: 1.e-4
  wd: 1.e-8
  num_ns: 2000
  neg_sampling_on_all: True
student:
  epochs: 1000
  batch_size: 256
  lr: 1.e-4
  wd: 1.e-8
  num_ns: 2000
  neg_sampling_on_all: True