teacher:
  bpr:
    init_std: 1.e-2
    embedding_dim: 20
  bm3:
    embedding_dim: 500
    n_layers: 2
    reg_weight: 0.0001
    cl_weight: 5
    dropout: 0.5
student:
  init_std: 1.e-3
  embedding_dim: 20