teacher:
  bpr:
    init_std: 1.e-2
    embedding_dim: 20
  bm3:
    embedding_dim: 1000
    n_layers: 2
    reg_weight: 0.0001
    cl_weight: 10
    dropout: 0.5
  lgmrec:
    embedding_dim: 1000
    n_ui_layers: 2
    n_mm_layers: 1
    n_hyper_layer: 1
    hyper_num: 4
    alpha: 0.1
    reg_weight: 0.0001
    cl_weight: 5
    dropout: 0.5
  mgcn:
    embedding_dim: 1000
    n_ui_layers: 2
    knn_k: 5
    n_mm_layers: 1
    reg_weight: 1.e-6
    cl_weight: 0.01
student:
  init_std: 1.e-3
  embedding_dim: 100