bm3:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-3
  lmbda: 0.5
  fitnet_norm: False
  dropout_rate: 0.5
  hidden_dim_ratio: 0.5
lgmrec:
  epochs: 1000
  batch_size: 2048
  lr: 1.e-3
  wd: 1.e-3
  lmbda: 0.05
  fitnet_norm: False
  dropout_rate: 0.5
  hidden_dim_ratio: 5