teacher:
  model: GateCrossNet
  embedding_dim: 20
  L2: 0
  depth: 6
student:
  # model: DNN
  # embedding_dim: 20
  # L2: 1.e-5
  # hidden_dims: [64, 32, 1]
  # dropout: 0.1
  
  model: GateCrossNet
  embedding_dim: 20
  L2: 0
  depth: 2