teacher:
  model: CrossNet
  embedding_dim: 20
  L2: 1.e-5
  hidden_dims: [1000, 1000, 1000, 1000, 1000, 1]
  dropout: 0.1
  cin_dims: [200, 200, 200]
student:
  model: DNN
  embedding_dim: 20
  L2: 1.e-5
  hidden_dims: [64, 32, 1]
  dropout: 0.1