teacher:
  model: DCNv2
  batch_norm: true
  embedding_dim: 20
  embedding_regularizer: 1.0e-05
  dnn_activations: relu
  parallel_dnn_hidden_units: [1000, 1000, 1000, 1000, 1000]
  net_dropout: 0.1
  net_regularizer: 0
  model_structure: parallel
  num_cross_layers: 3
  num_experts: 4
student:
  model: DNN
  batch_norm: false
  embedding_dim: 20
  embedding_regularizer: 1.0e-05
  hidden_activations: relu
  hidden_units: [32]
  net_dropout: 0.2
  net_regularizer: 0