teacher:
  model: DCNv2
  embedding_dim: 20
  L2: 1.e-5
  hidden_dims: [1000, 1000, 1000, 1000, 1000, 1]
  dropout: 0.1
  depth: 4
student:
  model: DNN
  embedding_dim: 20
  L2: 1.e-5
  hidden_dims: [32, 1]
  dropout: 0.1